// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi93XsuLcOx8GTmSWIE9_AbxC_AdYHezo',
    appId: '1:424361835452:web:afe34f6b1703301473c9b9',
    messagingSenderId: '424361835452',
    projectId: 'blood-bank-99595',
    authDomain: 'blood-bank-99595.firebaseapp.com',
    storageBucket: 'blood-bank-99595.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtrnm9qsbgSWjIscXR9eajh2z2xCPA9Us',
    appId: '1:424361835452:android:ae092b7c1392f12773c9b9',
    messagingSenderId: '424361835452',
    projectId: 'blood-bank-99595',
    storageBucket: 'blood-bank-99595.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsJjtclSebRtT3FyQiP2L07N7EC1_kKDA',
    appId: '1:424361835452:ios:e93ccbb58e509ba973c9b9',
    messagingSenderId: '424361835452',
    projectId: 'blood-bank-99595',
    storageBucket: 'blood-bank-99595.firebasestorage.app',
    iosClientId: '424361835452-jkhj3gdlhkvfg5q8qk91nokd8gkjks9m.apps.googleusercontent.com',
    iosBundleId: 'com.bloodBank.app',
  );
}
